#!/bin/bash

#if [[ $1 != "" ]] then
rm -r AllPrograme.class 2> /dev/null
rm -r AllPrograme.java 2> /dev/null
echo "" > AllPrograme.java
echo "class AllPrograme{" >> AllPrograme.java
echo "    public static void main(String... s){" >> AllPrograme.java

n=$(ls --sort none *.class | wc -w)
echo $n
for (( i=1 ; i<=$n ; i++ ));
do
	className=$(ls --sort none *.class | tr " " "\n" | head "-$i" | tail -1 | tr "." " " | awk '{print $1}')
	echo "        $className.main();" >> AllPrograme.java
	echo "        System.out.println();"
done
echo "    }" >> AllPrograme.java
echo "}" >> AllPrograme.java
