#!/bin/bash

VERBOOSE="false"

if [ -n "$(echo $1 | grep -i true)" ]; then
	VERBOOSE="true"
else
	VERBOOSE="false"
fi

MYDIR_ROOT="/home/sonu"
MYGIT_ROOT="github.com/sonoou/"
MYGIT_DIR=(customCommand Desktop/Java_Manish_sir Desktop/myprojects Desktop/Books_and_Notes/C_lang)
MYGIT_REPO=(custom_command Java_Practice myprojects C_lang)
MYGIT_LOG="${MYDIR_ROOT}/.auto-git-push-log.txt"


make_push(){
	#echo -e "Pushing objects to ${1} \t\t\c"

	TIME="$(date +'%d%b%Y, %I:%M%p')"
	echo "[${TIME}]" >> "${MYGIT_LOG}"

	echo "adding objects to ${1}.git" >> "${MYGIT_LOG}"
	git add *
	if [ $? -eq 0 ]; then
		if [ "${VERBOOSE}" == "true" ]; then
			echo "added successfully"
			echo "commiting object to ${1}.git"
		fi
	else
		echo -e "\033[1;38;5;9m[ERROR]:\033[0m see logs ${MYGIT_LOG}"
		exit 1
	fi

	git commit -m "${TIME}"
	if [ $? -eq 0 ]; then
		if [ "${VERBOOSE}" == "true" ]; then
			echo "commited successfully"
			echo "pushing object to ${1}.git"
		fi
	else
		echo -e "\033[1;38;5;9m[ERROR]:\033[0m see logs ${MYGIT_LOG}"
		exit 1
	fi

	git push "https://${MYGIT_USER}:${MYGIT_PASS}@github.com/sonoou/${1}.git" 2>> "${MYGIT_LOG}"
	if [ $? -eq 0 ]; then
		if [ "${VERBOOSE}" == "true" ]; then
			echo "pushed successfully"
		fi
	else
		echo -e "\033[1;38;5;9m[ERROR]:\033[0m see logs ${MYGIT_LOG}"
		exit 1
	fi

	echo -e "\n\n\c" >> "${MYGIT_LOG}"
}

for(( i=0 ; i<=${#MYGIT_DIR[@]} ; i++ ))
do
		if [ "${VERBOOSE}" == "true" ]; then
			echo "pushed successfully"
		fi
	echo "going to ${MYDIR_ROOT}/${MYGIT_DIR[i]}"
	cd "${MYDIR_ROOT}/${MYGIT_DIR[i]}"
	make_push "${MYGIT_REPO[i]}"
done


