#!/bin/bash

XAXIS=100
YAXIS=520

MTIME="0.1"

xdotool mousemove $XAXIS $YAXIS
xdotool click 1
sleep $MTIME
xdotool mousemove $(( XAXIS + 80 )) $(( YAXIS + 55 ))
sleep $MTIME
xdotool click 1
sleep $MTIME
xdotool key BackSpace
sleep $MTIME
xdotool type "Cantarell"
sleep $MTIME
xdotool key Return
sleep $MTIME
xdotool key Escape
sleep $MTIME
xdotool mousemove $(( XAXIS + 1000 )) $(( YAXIS + 150 ))
sleep $MTIME
xdotool click 1
sleep $MTIME
xdotool mousemove $(( XAXIS + 790 )) $(( YAXIS + 150 ))
sleep $MTIME
xdotool click 1
sleep $MTIME
xdotool mousemove $(( XAXIS + 790 )) $(( YAXIS + 220 ))
sleep $MTIME
xdotool click 1
sleep $MTIME
xdotool mousemove $(( XAXIS + 890 )) $(( YAXIS + 150 ))
sleep $MTIME
xdotool click 1
sleep $MTIME
xdotool type "0.8"
sleep $MTIME
xdotool key Return
sleep $MTIME
xdotool mousemove $(( XAXIS + 890 )) $(( YAXIS + 230 ))
sleep $MTIME
xdotool click 1
sleep $MTIME
xdotool type 0
sleep $MTIME
xdotool key Return
sleep $MTIME
xdotool mousemove $(( XAXIS + 1000 )) $(( YAXIS + 150 ))
sleep $MTIME
xdotool click 1
