#!/bin/bash

VERBOOSE="false"

MYDIR_ROOT="/home/sonu"
MYGIT_ROOT="github.com/sonoou/"
MYGIT_DIR=(customCommand Desktop/Java_Manish_sir Desktop/myprojects Desktop/Books_and_Notes/C_lang)
MYGIT_REPO=(custom_command Java_Practice myprojects C_lang)

make_push(){
	echo -e "Pushing objects to ${1} \t\t\c"
	TIME="$(date +'%d%b%Y, %I:%M%p')"
	echo "[${TIME}]" >> ${MYDIR_ROOT}/customCommand/auto-git-push-log.txt
	echo "Pushing objects to ${1}" >> ${MYDIR_ROOT}/customCommand/auto-git-push-log.txt
	git add *
	git commit -m "${TIME}"
	git push "https://${MYGIT_USER}:${MYGIT_PASS}@github.com/sonoou/${1}.git" 2>> ${MYDIR_ROOT}/customCommand/auto-git-push-log.txt
	echo -e "\n\n\c" >> ${MYDIR_ROOT}/customCommand/auto-git-push-log.txt
	if [ $? -eq 0 ]; then
		exit 1
	fi
}

for(( i=0 ; i<=${#MYGIT_DIR[@]} ; i++ ))
do
	echo "going to ${MYDIR_ROOT}/${MYGIT_DIR[i]}"
	cd "${MYDIR_ROOT}/${MYGIT_DIR[i]}"
	make_push "${MYGIT_REPO[i]}"
done


