#!/bin/bash

xdotool mousemove 100 550
xdotool click 1
sleep 0.1
xdotool mousemove 180 600
xdotool click 1
xdotool key BackSpace
#sleep 0.5
xdotool type "Cantarell"
#sleep 0.5
xdotool key Return
sleep 0.4
xdotool key Escape
sleep 0.4
xdotool mousemove 1090 690
xdotool click 1
xdotool mousemove 890 690
xdotool click 1
sleep 0.1
xdotool mousemove 890 770
xdotool click 1
xdotool mousemove 990 691
xdotool click 1
xdotool type "0.9"
sleep 0.4
xdotool key Return
sleep 0.1
xdotool mousemove 990 770
xdotool click 1
xdotool type 0
xdotool key Return
xdotool mousemove 1090 690
xdotool click 1
