#!/bin/bash

INSTALLED_JDKS=$(ls /usr/lib/jvm | tr " " "\n" | cat -n)
TOTAL_JDKS=$(echo "$INSTALLED_JDKS" | tail -1 | awk '{print $1}')
OUT=$(javac -version 2>&1)
if [ "$(echo $OUT | grep -o javac)" != "javac" ]; then
	OUT=$(javac --version 2>&1)
fi
currPath=$(echo "$OUT" | awk '{print $2}')
CURR_JDK_NUM=$(echo "$INSTALLED_JDKS" | grep "$currPath" | awk '{print $1}')
INSTALLED_JDKS_COLOR=""
for (( i=1; i<=$TOTAL_JDKS; i++ ))
do
	JDK=$(echo "$INSTALLED_JDKS" | head "-$i" | tail -1)
	if [ -n "$(echo $JDK | grep $currPath)" ]; then
		INSTALLED_JDKS_COLOR=$(echo "$INSTALLED_JDKS_COLOR\n\033[1;38;5;10m$JDK\033[0m")
	else
		INSTALLED_JDKS_COLOR=$(echo "$INSTALLED_JDKS_COLOR\n$JDK")
	fi
done
echo -e "$INSTALLED_JDKS_COLOR"
echo -e "     5  Exit"
echo -e "\n\tPlease enter index no: \c"

read newPath
if echo "$newPath" | grep -q '[^0-9]'; then
	echo -e "\tonly number is allowed"
	chjava
	exit
elif [ -z "$newPath" ]; then
	echo -e "\tonly number is allowed"
	chjava
	exit
elif [ $newPath -eq 5 ]; then
	echo "Bye"
	exit
fi

jPath=$(echo "$INSTALLED_JDKS" | head "-$newPath" | tail -1 | awk '{print $2}')

if [ -n "$(echo $jPath | grep $currPath)" ]; then
	echo -e "\nThis JDK $jPath is already in PATH variable. \nchoose different\c" 
	chjava
	exit
fi

rm -r /usr/lib/my-default-jdk/*
ln -s /usr/lib/jvm/$jPath/bin/* /usr/lib/my-default-jdk/

# check version
echo "javac output:"
OUT=$(javac -version 2>&1)
if [ "$(echo $OUT | grep -o javac)" == "javac" ]; then
	echo "$OUT"
else
	javac --version
fi
echo
echo "java output:"
OUT=$(java -version 2>&1)
if [ "$(echo $OUT | grep -o java)" == "java" ]; then
	echo "$OUT"
else
	java --version
fi
