#!/bin/bash

n=$(find /home/sonu/Desktop/Java_Manish_sir -name incomplete.txt | cat -n | awk '{print $1}' | tail -1)

for (( i=1 ; i<=n ; i++ ));
do
	echo -e "\n\033[1;38;5;1m$(find /home/sonu/Desktop/Java_Manish_sir -name incomplete.txt | head -$i | tail -1)\n\033[0m\033[1;38;5;7m"
	cat $(find /home/sonu/Desktop/Java_Manish_sir -name incomplete.txt | head -$i | tail -1)
done
