#!/bin/bash

#echo -e "Enter your line : \c"
#read input
#echo  $1
#totalLine=$(echo $1 | wc -l)
#echo "total lines are $totalLine"

nano /__prettyTemp__
totalLine=$(cat /__prettyTemp__ | wc -l)
maxChars=0

for (( i=1 ; i<=$totalLine ; i++))
do
	ch=$(cat /__prettyTemp__ | head "-$i" | tail -1 | wc -m)
	if [ $maxChars -lt $ch ]; then
		maxChars=$ch
	fi
done

HEAD_CAP=$(printf "┌")
for (( j=1 ; j<=$maxChars-1 ; j++ ))
do
	HEAD_CAP=$(printf "$HEAD_CAP─")
done
HEAD_CAP=$(printf "$HEAD_CAP┐\n")

echo -e "$HEAD_CAP"

for (( i=1 ; i<=$totalLine; i++))
do
	space="-"
	curLineChars=$(cat /__prettyTemp__ | head "-$i" | tail -1 | wc -m)
	(( finalChars=$maxChars-$curLineChars-1 ))
	for (( j=1 ; j<=$finalChars ; j++))
	do
		space=$(echo "$space-")
	done
	space=$(echo $space | awk '{gsub("-"," ");} 1')
	if [ $finalChars -eq -1 ]; then
		space=""
	fi
	echo "│$(cat /__prettyTemp__ | head -$i | tail -1)$space│"
#	echo "│""$(cat /__prettyTemp__ | head -$i | tail -1)""$space│"
done

#printf "└"
#for (( j=1 ; j<=$maxChars-1 ; j++ ))
#do
#	printf "─"
#done
#printf "┘\n"
printf "$HEAD_CAP" | awk '{gsub("┌","└");} 1' | awk '{gsub("┐","┘");} 1'
rm /__prettyTemp__
