#!/usr/bin/bash


echo -e "Enter your enrollment no: \c"
read enroll
echo -e "Enter subject code: \c"
read subj

echo -e "\033[1;38;5;2m  Sub. Code     Assign.    TET       TEP         STATUS\033[0m"
curl -sS  "https://gradecard.ignou.ac.in/gradecard/view_gradecard.aspx?eno=$enroll&prog=BCA&type=1" | grep -i "$subj" | awk '{print $4,$7,$22,$25,$28,$29}' | awk '{gsub("size=\"4\">","   ");gsub(">",""); gsub("font"," "); gsub("<",""); gsub("td"," "); gsub("/","") } 1'
