#!/usr/bin/bash

#######################
#### Using kdialog ####
#######################

value=$(kdialog --radiolist "Choose an option" shutdown "Shutdown" on sleep "Sleep" off reboot "Reboot" off --geometry 300x200+615+330)

if [ "$value" = shutdown ] ; then
	shutdown now
elif [ "$value" = sleep ] ; then
   	systemctl suspend
elif [ "$value" = reboot ] ; then
   	reboot
else
   	echo ""
fi
