#!/usr/bin/bash

clear
DOM_HOME=/home/sonu/Oracle/Middleware/Oracle_Home/user_projects/domains
export TZ=IST
if [ "$1" == "start" ]; then
	ls $DOM_HOME | tr " " "\n" | cat -n
	TOTAL_DOM=$(ls $DOM_HOME | tr " " "\n" | cat -n | awk '{print $1}' | tail -1)
	echo -e "Which one(number): \c"
	read no
	if [ $no -lt 1 ] || [ $no -gt $TOTAL_DOM ]; then
		echo "Wrong input"
		exit 0
	fi
	DOM=$(ls $DOM_HOME | tr " " "\n" | cat -n | head "-$no" | tail -1 | awk '{print $2}')
	$DOM_HOME/$DOM/startWebLogic.sh
fi

if [ "$1" == "config" ]; then
	$DOM_HOME/../../oracle_common/common/bin/config.sh
fi
